name: Android CI

on:
  push:
    branches:
      - *
      - feature/CI
      - master
  pull_request:
    branches:
      - master
      - *

jobs:
  format:
    name: Google Java Format
    runs-on: ubuntu-latest
    steps: 
    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v2.0.0
    
  build:
    name: Build with Gradle
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
  
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04
    needs: [build]

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
